      
server:
  port: 8080
  contextPath: /wii
  
hibernate:
    showSql: true
    dialect: org.hibernate.dialect.Oracle10gDialect
    
spring:
    thymeleaf.cache: false
    thymeleaf.check-template: true
    thymeleaf.check-template-location: true
    thymeleaf.content-type: text/html
    thymeleaf.enabled: true
    thymeleaf.encoding: UTF-8
